#!/bin/sh
#
# Copies available custom user network config files to the rootfs
#

USER_FOLDER="/media/fat/linux/network"
HOSTNAME_USER_FILE="${USER_FOLDER}/hostname"
HOSTS_USER_FILE="${USER_FOLDER}/hosts"
DHCP_USER_FILE="${USER_FOLDER}/dhcpcd.conf"
INTERFACES_USER_FILE="${USER_FOLDER}/interfaces"

HOSTNAME_FILE="/etc/hostname"
HOSTS_FILE="/etc/hosts"
DHCP_FILE="/etc/dhcpcd.conf"
INTERFACES_FILE="/etc/network/interfaces"

# Copy a file if the source exists and the destination is different
# $1 - source file
# $2 - destination file
copy() {
  if [ -f "$1" ]; then
    if [ -f "$2" ]; then
      if cmp -s "$1" "$2"; then
        return 0
      else
        cp "$1" "$2"
      fi
    else
      cp "$1" "$2"
    fi
  fi
}

start() {
  mount -o remount,rw /
  copy "${HOSTNAME_USER_FILE}" "${HOSTNAME_FILE}"
  cat "${HOSTNAME_FILE}" > /proc/sys/kernel/hostname
  copy "${HOSTS_USER_FILE}" "${HOSTS_FILE}"
  copy "${DHCP_USER_FILE}" "${DHCP_FILE}"
  copy "${INTERFACES_USER_FILE}" "${INTERFACES_FILE}"
  mount -o remount,ro /
}

case "$1" in
  start)
    "$1";;
  stop)
    ;;
  restart|reload)
    start;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac
