#!/bin/sh

SYSLOGD_ARGS=-n
KLOGD_ARGS=-n
[ -r /etc/default/logging ] && . /etc/default/logging

start() {
	printf "Disable CPU1"
	echo 0 > /sys/devices/system/cpu/cpu1/online
}

stop() {
	printf "Enable CPU1"
	echo 1 > /sys/devices/system/cpu/cpu1/online
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
